apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: newnginx
      image: nginx
      env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: PORT
  